#!/usr/bin/env node

const yamljs = require("yamljs")
    , axios = require("axios")
    , path = require("path")
    , fs = require("fs")
    , LANGUAGES_YML_URL = "https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml"
    , DESTINATION_PATH = path.resolve(__dirname, "../data/languages.js");

(async () => {

    try {

        const response = await axios.get(LANGUAGES_YML_URL)
            , yaml = yamljs.parse(response.data)
            , json = JSON.stringify(yaml, null, 4);

        fs.writeFileSync(DESTINATION_PATH, `module.exports = ${json};`);

    } catch (err) {

        console.error("- failed to fetch and parse languages yml", err);

    }
})();